### PR TITLE
Fix for dev stringr

### PR DESCRIPTION
**Pull request by hadley**
This fixes a failure due to `str_detect(x, pattern = "")` now erroring. I also made some other changes to make sure your package cleanly passes `R CMD check` to ensure that I fixed everything correctly.

### CODE REVIEW

**Comment by hope-data-science** [comment]
Thank you for noting. Sorry that I am not familiar with git. May I ask what should I do to update the package so as to make it error free? Thanks.

**Comment by hadley** [comment]
You just need to merge this PR and then resubmit to CRAN.

**Comment by hope-data-science** [comment]
Problem is, I have just updated a version of 1.7.4, and your revisions have made on the previous version 1.7.3, which I have not updated immediately. Can you tell me which files are updated so I can just merge and replace them accordingly, but still save the latest updates?

**Comment by hadley** [comment]
The only critical change you need to make is this line: https://github.com/hope-data-science/tidyfst/pull/21/files#diff-cd1f660cc0bb933dffc0b7755837c1af4248f6a0618500582682a9625fcbdc85R26

**Comment by hope-data-science** [comment]
Thank you for noting, I will try to merge the two branches locally and resubmit to CRAN. I'll update the git version as soon as possible to make the two version consistent. Thanks.

**Comment by hadley** [comment]
FYI stringr is now scheduled for release to CRAN on Dec 2.

**Pull request merged**
